### ISSUE TITLE
Ill conditioned data matrices - Checks and Regularization

### ISSUE THREAD

**Issue by adam2392** [PyDMD/PyDMD#107]
Hi,

so I ran into an issue w/ my data matrices being fed in and there is are numerical issues when your X is ill-conditioned (e.g. > 10^4), then the SVD approach will surely fail. My runs give me basically useless A matrices.

Had two questions:

1. Any suggestions on how we might incorporate regularization into the code elegantly? I'm thinking something like L2 regularization should be sufficient, with a passed in parameter.
2. I plan on incorporating a few lines just to check the condition number of the X matrix. Any concerns on me doing this? Thinking something along the lines of 

"if cond > THRESHOLD: raise warning."

**Comment by mtezzele** [comment]
#108 addresses point 2. 
For what concerns point 1 I would add something in the `_col_major_2darray(X)` method. Are you aware of some literature doing regularization before applying DMD? In case we can refer to that I suppose.
