### ISSUE TITLE
Prediction with DMDc

### ISSUE THREAD

**Issue by evenlund** [PyDMD/PyDMD#292]
I am experimenting a bit with DMD with control and wonder whether it is possible to do future prediction (similar to tutorial 2) with DMDc?

When I just try to expand time, like in the forementioned example I get the following error:
"RuntimeError: The number of control inputs and the number of snapshots to reconstruct has to be the same"

I am not providing a control input for the prediction period, but if I can set this to be an extension of the past (constant value) that will suffice.

A code example would be tutorial 7, with this line added, to look 3 timesteps into the future:

`dmdc.dmd_time['tend']+=3*dmdc.dmd_time['dt']`

**Comment by moonlians** [comment]
Does this work?
Will it extend the last value of the past inputs, even if it wasn't constant before?

**Comment by mtezzele** [comment]
Hi @moonlians, could you provide a small script for your error?
The DMD with control needs the control inputs for all the future time instants you want to predict.

**Comment by moonlians** [comment]
Amazing, totally missed that. Thank you!
