### ISSUE TITLE
PiDMD - SVD Truncation

### ISSUE THREAD

**Issue by neox395** [PyDMD/PyDMD#404]
**Describe the bug**
Setting the rank truncation to automatic (_svd_rank = 0_) for optimal truncation leads to a ValueError exception, hinting a dimension missmatch [here](https://github.com/PyDMD/PyDMD/blob/4be0d1ef0b64058ad9f2193b96a5dd04b8a4c671/pydmd/pidmd.py#L204).

**To Reproduce**
`# arbitrary input_x of shape [96, 12] in testing environment`
`pidmd = PiDMD("symmetric", compute_A=true, svd_rank=0)`
`pidmd.fit(input_x)`

**Expected behavior**
Perform a rank reduced decomposition, s.t. svd_rank < 11.

**Output**
File "/home/dmd/.local/lib/python3.11/site-packages/pydmd/pidmd.py", line 204, in compute_operator
    self._modes = U.dot(self._eigenvectors)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: shapes (96,1) and (11,11) not aligned: 1 (dim 1) != 11 (dim 0)

**Comment by mtezzele** [comment]
@sichinaga could you please look into it?

**Comment by sichinaga** [comment]
@mtezzele I'll address this asap!

**Comment by mtezzele** [comment]
Thank you @neox395 for reporting this issue. Now it is fixed thanks to @sichinaga.
