### ISSUE TITLE
plot_eigs method does not seem to work

### ISSUE THREAD

**Issue by evenlund** [PyDMD/PyDMD#455]
After installing the latest version of pydmd today 22.08.23 I get the error "AttributeError: 'DMD' object has no attribute 'plot_eigs'" when calling DMD.plot_eigs()

The issue can be tested by following tutorial1

**Comment by mtezzele** [comment]
Hi @evenlund could you please tell us the exact line of tutorial 1? I don't see the command you are referring to.

**Comment by mtezzele** [comment]
In [ tutorials/tutorial1/tutorial-1-dmd.ipynb](https://github.com/PyDMD/PyDMD/blob/6460dab2b75422ca28a1685d5a8beada23975b2f/tutorials/tutorial1/tutorial-1-dmd.ipynb) you can see we use `plot_eigs` as a separate method that takes a dmd instance as argument. Some months ago we changed the API, so now all the plotting functionalities are in a separate module. Let me know if tutorial 1 is not working on your side.

**Comment by evenlund** [comment]
Yes, I was referring to the .ipynb-code. I have tested now with the regular python code for tutorial 1 and that is working fine. I will rewrite my code accordingly. Thank you for clarifying!
