### ISSUE TITLE
How to use ParametricDMD with BOPDMD?

### ISSUE THREAD

**Issue by zonexo** [PyDMD/PyDMD#460]
Hi,

I have managed to get ParametricDMD working with the vanilla DMD.

However, when I tried to use it with BOPDMD, I got an error:

```
pdmd_monolithic.fit(training_snapshots, training_params)

TypeError: fit() missing 1 required positional argument: 't'
```

I understand that BOPDMD requires an additional argument:

```
optdmd = BOPDMD(svd_rank=svd_rank_bop, num_trials=0)
        optdmd.fit(snapshots, snapshots_time)
```

So how should I add snapshots_time to pdmd_monolithic.fit to get it working?

Thanks!

**Comment by fandreuz** [comment]
Closing as duplicated of #461
