### ISSUE TITLE
Redundant SVD computation

### ISSUE THREAD

**Issue by greinerth** [PyDMD/PyDMD#471]
I noticed that in function [compute_svd](https://github.com/PyDMD/PyDMD/blob/065dccfed3e9b258901cef0fafb10ecd97ea5e9c/pydmd/utils.py#L82l), 
SVD is executed two times since function [compute_rank](https://github.com/PyDMD/PyDMD/blob/065dccfed3e9b258901cef0fafb10ecd97ea5e9c/pydmd/utils.py#L9) also computes an SVD. Instead, one time should be sufficient. If the data is very highly dimensional this is likely a computational overhead (runtime and probably memory profile).

It should be possible to rewrite such that the redundant computation can be avoided.

**Comment by ndem0** [comment]
Thanks for having spotted the issue: you're right, actually SVD is computed twice. We will try to fix asap.

**Comment by greinerth** [comment]
Made a corresponding [PR](https://github.com/PyDMD/PyDMD/pull/472).
