### ISSUE TITLE
Zenodo DOI

### ISSUE THREAD

**Issue by roxyboy** [PyDMD/PyDMD#489]
Thank you for developing this awesome package!
Would it be possible for you to generate a Zenodo DOI so that I can cite the most recent version of PyDMD code in addition to the JOSS paper?

The only Zenodo DOI I found was https://doi.org/10.5281/zenodo.1171788 but this is linked to v0.1...

**Comment by sichinaga** [comment]
Hi @roxyboy! Thank you for the inquiry.

So the PyDMD developer team is actually currently in the process of developing a new paper for the v1.0 release! We anticipate that the paper will be released on arXiv very soon (specifically within the next week or so), so please stay tuned! We will be sure to link the new reference here as soon as it is released! 😃

**Comment by sichinaga** [comment]
Hi again @roxyboy! As promised, here is the [new PyDMD paper on arXiv](https://arxiv.org/abs/2402.07463). Thank you for your patience. 😄

**Comment by roxyboy** [comment]
Awesome! Thank you so much :)
