### ISSUE TITLE
Pre-processing for DMDc

### ISSUE THREAD

**Issue by elise1993** [PyDMD/PyDMD#553]
**Describe the bug**
Hello! Are the pre-processing methods not supported for DMDc models? Even a simple zero-mean pre-processing doesn't work; returning the error:

**Output**
> File ~\anaconda3\envs\dmdc\Lib\site-packages\pydmd\preprocessing\pre_post_processing.py:103 in _pre_processing_fit
>     self._pre_processing(self._state_holder, *args, **kwargs)
> 
> TypeError: _pre() got multiple values for argument 'axis'

Looks like this is because the pre-processing function only expects one dataset (the state snapshots), but is receiving two datasets (the state snapshots and input snapshots) from the DMDc model. Is this a bug or an unsupported feature?

**To Reproduce**
```
import numpy as np
from pydmd import DMD,DMDc
from pydmd.preprocessing import zero_mean_preprocessing

stateData = np.random.rand(10,100)
inputData = np.random.rand(1,100)

# works fine
dmd = DMD(svd_rank=0)
dmd = zero_mean_preprocessing(dmd)
dmd.fit(stateData)

# does not work
dmdc = DMDc(svd_rank=0)
dmdc = zero_mean_preprocessing(dmdc)
dmdc.fit(stateData,inputData[:,:-1])
```

Same problem/error with the other pre-processing methods.

Environment packages I have installed: [environment.zip](https://github.com/user-attachments/files/17546805/environment.zip) [same issue on both v1.0.1 and v1.0.0]

**Comment by fandreuz** [comment]
Hi @elise1993, thanks for reporting the problem. 

I've drafted a quick fix, could you please check whether it fixes your problem? You can test the new version with:
```bash
pip install git+https://github.com/PyDMD/PyDMD.git@pre-processing-dmdc
```

The installation may take several minutes, pip is going to temporarily clone the whole PyDMD repository.

**Comment by elise1993** [comment]
Yes! That worked! Thank you for the quick response/fix @fandreuz !
